language: go

matrix:
  fast_finish: true
  include:
    - go: 1.15.x
      env:
        - TESTTAGS=nomsgpack

git:
  depth: 10

before_install:
  - export GOPATH="${HOME}/go"

install:
  - go mod download
  - export PATH="${GOPATH}/bin:${GOROOT}/bin:${PATH}"
  - make tools

script:
  - make vet
  - make fmt-check
  - make misspell-check
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)
